# Generated by Django 2.2.7 on 2019-12-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0003_dishcount'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dishes_order',
        ),
        migrations.AddField(
            model_name='order',
            name='dish_ordered',
            field=models.ManyToManyField(through='dishes.DishCount', to='dishes.InstanceDish'),
        ),
    ]
