# Generated by Django 2.2.7 on 2019-12-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20191211_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='costumer_name',
            field=models.CharField(default='Unknown', max_length=100, verbose_name='Name'),
        ),
    ]
