# Generated by Django 2.2.7 on 2019-12-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceDish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Pizza')),
                ('description', models.TextField(max_length=255, verbose_name='Description')),
                ('is_vegan', models.BooleanField(verbose_name='Vegan')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price')),
                ('weight', models.IntegerField(verbose_name='Weight, grams')),
                ('calories', models.IntegerField(verbose_name='Calories')),
            ],
        ),
    ]
