# Generated by Django 2.2.7 on 2019-12-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instancedish',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Name'),
        ),
    ]
