# Generated by Django 2.2.7 on 2019-12-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0003_dishcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishcount',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Count'),
        ),
    ]
